config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get "/journeys/:id/preview", to: "journeys#preview", as: :preview
  get '/profile', to: 'profiles#show'
  root to: 'pages#home'
  resources :journeys
  resources :venues do
    resources :journey_venues, only: %i[create]
  end
  resources :journey_venues, only: %i[destroy]
  resources :cities, only: %i[index show new create]

  # post "/cities/:id", to: "journeys#add_venue", as: :add_venue
  # delete "/cities/:id", to: "journeys#remove_venue", as: :remove_venue
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_journey_button.html.erb
<% journey = current_user.journeys.empty? ? Journey.create(user: current_user) : current_user.journeys.last %>
<a href="<%= journey_path(journey) %>" class="btn journey-button">
  My Journey
  <% if journey.venues.count > 0 %>
    <p id="journey-notification">
      <%= journey.venues.count %>
    </p>
  <% end %>
</a>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-dark navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <h2>Kanaku</h2>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto nav-right">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "All Journeys", journeys_path, class: "nav-link" %>
          </li>
           <li class="nav-item active">
            <% @journey = current_user.journeys.nil? ? Journey.create(user: current_user) : current_user.journeys.last%>
            <%= link_to "My Journey", journey_path(@journey), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Add Venue", new_venue_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= link_to current_user.first_name, "#", class: "nav-link", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", profile_path, class: "dropdown-item" %>
              <%= link_to "Settings", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<%#_____________________________________________SEARCH BAR____________________________________________________________%>

<div class="search-box-container" data-controller="searchBar">
  <div class="search-box" data-searchBar-target="box" data-action="touchstart->searchBar#toggleTouchStart">
    <%# <button class="btn-magnifying" data-action="focus->searchBar#visibility blur->searchBar#visibility">
      <i class="fas fa-search" data-searchBar-target="magnify"></i>
    </button> %>
    <p class="search-header" data-searchBar-target="placeholder">Search</p>
    <%= form_tag root_path, method: :get, class: "d-flex p-0 justify-content-center" do %>
      <%= text_field_tag :city,
        params[:city],
        class: "input-search",
        placeholder: "",
        id: "basic-addon2", autocomplete: "off",
        data: {searchBar_target: "inputc", action: "blur->searchBar#toggleBlurCity focus->searchBar#toggleFocusCity"}
        # , autofocus: true
        # data: {searchBar_target: "inputc"},
      %>
      <%= text_field_tag :venue,
        params[:venue],
        class: "input-search",
        placeholder: "",
        id: "basic-addon2", autocomplete: "off",
        data: {searchBar_target:"inputv", action: "blur->searchBar#toggleBlurVenue focus->searchBar#toggleFocusVenue"}
      %>
    <%= submit_tag "Search", class: "btn btn-primary d-none", id: "basic-addon2" %>
    <% end %>
  </div>
   <%# <button class="btn-search d-none" data-searchBar-target="magnify" data-action="click->searchBar#visibleAction">
    <i class="fas fa-search"></i>
  </button> %>
</div>
<%# blur->searchBar#visibility %>

app/views/shared/_new_navbar.html.erb
<%# <div class="page"> %>
  <%# <header tabindex="0" style="z-index: 1;"><%= link_to root_path, class: "navbar-brand" do %>
                                             <%# <h2>Kanaku</h2> %>
                                          <%# <% end%>

<header tabindex="0" style="z-index: 1;">
  <%= link_to root_path do %>
    <%= image_tag("https://res.cloudinary.com/wvala/image/upload/v1655130229/Kanaku_lwce8r.jpg", crop: :fit, class: "logo") %>
  <% end %>
</header>

<div id="nav-container" data-controller="navbar">
  <div class="bg"></div>
  <div class="button" style="z-index: 1;" tabindex="0" data-navbar-target="burger" data-action="focus->navbar#hideSearch blur->navbar#showSearch">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <%# <i class="fa-solid fa-less-than" id="icon-bar"></i> %>
  </div>
  <div id="nav-content" tabindex="0">
    <ul>
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "All Journeys", journeys_path, class: "nav-link" %>
        </li>
        <%# <li class="nav-item active"> %>
          <%# <% journey = current_user.journeys.empty? ? Journey.create(user: current_user) : current_user.journeys.last %>
          <%# <%= link_to "My Journey", journey_path(journey), class: "nav-link" %>
          <%# <% if current_user.journeys.nil? %>
            <%#= link_to "New Journey", journeys_path(user: current_user), method: :post, class: "nav-link" %>
          <%# else %>
            <%#= link_to "My Journey", journeys_path(current_user.journeys.last), class: "nav-link" %>
          <%# end %>
        <%# </li> %>
        <li class="nav-item active">
          <%= link_to "Add Venue", new_venue_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "My Profile", profile_path, class: "nav-link" %>
        </li>
        </li class="nav-item active">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link", id: "logout-btn" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<div class="clear"></div>

<%# </div> %>

app/views/shared/_search_bar_home.html.erb
<div class="search-box-container" data-controller="searchBar">
  <div class="search-box" data-searchBar-target="box" data-action="touchstart->searchBar#toggleTouchStart">
    <%# <button class="btn-magnifying" data-action="focus->searchBar#visibility blur->searchBar#visibility">
      <i class="fas fa-search" data-searchBar-target="magnify"></i>
    </button> %>
    <p class="search-header" data-searchBar-target="placeholder">Search</p>
    <%= form_tag root_path, method: :get, class: "d-flex p-0 justify-content-center" do %>
      <%= text_field_tag :city,
        params[:city],
        class: "input-search hidden-value",
        placeholder: "",
        value: "",
        id: "basic-addon2", autocomplete: "off",
        data: {searchBar_target: "inputc", action: "blur->searchBar#toggleBlurCity focus->searchBar#toggleFocusCity"}
        # , autofocus: true
        # data: {searchBar_target: "inputc"},
      %>
      <%= text_field_tag :venue,
        params[:venue],
        class: "input-search hidden-value",
        value: "",
        placeholder: "",
        id: "basic-addon2", autocomplete: "off",
        data: {searchBar_target:"inputv", action: "blur->searchBar#toggleBlurVenue focus->searchBar#toggleFocusVenue"}
      %>
    <%= submit_tag "Search", class: "btn btn-primary d-none", id: "basic-addon2" %>
    <% end %>
  </div>
   <%# <button class="btn-search d-none" data-searchBar-target="magnify" data-action="click->searchBar#visibleAction">
    <i class="fas fa-search"></i>
  </button> %>
</div>