config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get "/journeys/:id/preview", to: "journeys#preview", as: :preview
  get '/profile', to: 'profiles#show'
  root to: 'pages#home'
  resources :journeys
  resources :venues do
    resources :journey_venues, only: %i[create]
  end
  resources :journey_venues, only: %i[destroy]
  resources :cities, only: %i[index show new create]

  # post "/cities/:id", to: "journeys#add_venue", as: :add_venue
  # delete "/cities/:id", to: "journeys#remove_venue", as: :remove_venue
end

app/models/venue.rb
class Venue < ApplicationRecord
  belongs_to :city
  has_many :journey_venues, dependent: :destroy
  has_many :venue_categories, dependent: :destroy
  has_many :journeys, through: :journey_venues
  validates :city, :address, :name, presence: true
  validates :address, uniqueness: true

  has_many_attached :photos

  # geocoded_by :address
  # after_validation :geocode, if: :will_save_change_to_address?
  reverse_geocoded_by :latitude, :longitude
  include PgSearch::Model
  pg_search_scope :search_by_name,
                  against: %i[name],
                  using: {
                    tsearch: { prefix: true } # <-- now `superman batm` will return something!
                  }
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :find_venue, only: %i[edit show update destroy]

  def show
    if current_user.journeys.last.nil?
      @journey = Journey.create!(user: current_user)
      @journey.save
    end
    @journey_venue = JourneyVenue.find_by(journey: current_user.journeys.last, venue: @venue)

    @markers = [{ lat: @venue.latitude, lng: @venue.longitude, image_url: helpers.asset_url("marker-stroked.svg"), info_window: render_to_string(partial: "pages/info_window", locals: {venue: @venue }) }]
  end

  def new
    @venue = Venue.new
    @cities = City.all
  end

  def create
    @venue = Venue.new(venue_params)
    @venue.city = City.find(params[:venue][:city_id])

    @venue.save ? redirect_to(venue_path(@venue)) : render(:new)
  end

  def edit; end

  def update
    @venue.save ? redirect_to(venue_path(@venue)) : render(:new)
  end

  def destroy
    @venue.destroy
    redirect_to root_path
  end

  private

  def find_venue
    @venue = Venue.find(params[:id])
  end

  def venue_params
    params.require(:venue).permit(:address, :description, :name, photos: [])
  end
end

app/views/venues/_edit_form.html.erb
<%= simple_form_for @venue do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.submit "Update venue" %>
<% end %>

app/views/venues/_form.html.erb
<%= simple_form_for @venue do |f| %>
  <% unless @venue.persisted? %>
    <% @venue.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>
  <% end %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.association :city%>
  <%= f.input :description %>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <%= f.submit "Create venue" %>
<% end %>

app/views/venues/edit.html.erb
<h1>Update <%= @venue.name %></h1>

<%= render "edit_form", venue: @venue %>

app/views/venues/new.html.erb
<div class="container">
  <h1>Add a new venue</h1>
  <p>Please enter you venue's details below and click "Create venue" when you are finished</p>

  <%= render "form", venue: @venue %>
</div>

app/views/venues/show.html.erb
<%= render "shared/journey_button" %>
<div class="container show-container">
  <% if @venue.photos.attached? %>
    <% @venue.photos.each do |photo| %>
      <%= cl_image_tag photo.key, class: "venue-mini" %>
    <% end %>
  <% else %>
    <%# unsplash search result, first photo of city interpolated into the style %>
    <% @photo_url = Unsplash::Photo.search("restaurant").sample[:urls].regular%>
    <% @phto_url = "https://ychef.files.bbci.co.uk/976x549/p04dgkm4.jpg" if @photo_url.nil? || @photo_url.empty?%>
    <% @style = "background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(#{@photo_url});" %>
    <div class="venue-show-card-image" style="<%= @style %>">
      <p class="city-show-card-city-name" id="city"><%= @venue.name %></p>
    </div>
  <% end %>
 <div class="venue-holder">
  <div class="venue-show-card">
    <%# <% if @venue.photos.attached? %>
      <%# @venue.photos.each do |photo| %>
        <%# <div class="venue-image-container" style="<%="background-image: linear-gradient(to bottom, rgba(245, 246, 252, 0.1),rgba(245, 246, 252, 0.3),rgba(82, 82, 82, 0.7)),
                                                      url(#{image_tag photo.key, height: 150, width: 150, crop: :fill});"  %>
        <%# <%= @venue.name %>
        <%# </div>
      <% end %>
    <%# <% end %>
      <%# <% @venue.photos.each do |photo| %>
        <%# <%= cl_image_tag photo.key, class: "venue-photo" %>
      <%# <% end %>

    <div class="venue-description-container">
      <div>
        <%= link_to city_path(@venue.city), class: "mt-3 venue-show-card-city-name", id: "country" do %>
          <p> <span id="pin">📌</span> <%= @venue.city.name %></p>
        <% end %>
        <h6> <%= @venue.address %></h6>
      </div>
      <p><%= @venue.description %></p>
    </div>
    <div class="px-8">
      <div class="map-border" data-mapDisplay-target="mapb">
        <div style="width: 100vw; height: 50vh; position: absolute;" class="map"
          data-controller="mapbox"
          data-mapbox-markers-value="<%= @markers.to_json %>"
          data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    </div>
  </div>
</div>
  <div class="venue-button-container" id="">
  <%# data-controller="changer" %>
    <%# <a href="" class="btn btn-success" id="accept-venue">Add to previous</a>
    <a href="" class="btn btn-success" id="accept-venue"></a> %>
    <%= link_to city_path(@venue.city), class: "btn btn-success", id: "accept-venue" do %>
      <i class="gg-arrow-left"></i>
    <% end %>
    <% if @journey_venue %>
      <%= link_to journey_venue_path(@journey_venue), method: :delete, class: "btn btn-success", id: "reject-venue", data: {changer_target: "reject", action: "click->changer#setAccept"} do %>
        <i class="gg-trash"></i>
      <% end %>
    <% else %>
      <%= link_to venue_journey_venues_path(@venue), method: :post, class: "btn btn-success", id: "accept-venue", data: {changer_target: "accept", action: "click->changer#setReject"} do %>
        <i class="gg-add-r"></i>
      <% end %>
    <% end %>
  </div>
</div>