config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get "/journeys/:id/preview", to: "journeys#preview", as: :preview
  get '/profile', to: 'profiles#show'
  root to: 'pages#home'
  resources :journeys
  resources :venues do
    resources :journey_venues, only: %i[create]
  end
  resources :journey_venues, only: %i[destroy]
  resources :cities, only: %i[index show new create]

  # post "/cities/:id", to: "journeys#add_venue", as: :add_venue
  # delete "/cities/:id", to: "journeys#remove_venue", as: :remove_venue
end

app/models/journey.rb
class Journey < ApplicationRecord
  belongs_to :user
  has_many :journey_venues, dependent: :destroy
  has_many :venues, through: :journey_venues
  validates :user, presence: true
end

app/controllers/journeys_controller.rb
class JourneysController < ApplicationController
  before_action :find_journey, only: %i[edit update show preview]
  before_action :find_venue, only: %i[add_venue remove_venue]

  def index
    @journeys = current_user.journeys
  end

  def show
    # @markers = [{ lat: 48.847387, lng: 2.340593 }, { lat: 48.854467, lng: 2.345068 }, { lat: 48.860365, lng: 2.338580 }]
    @journey_venues = @journey.journey_venues

    @venues = @journey.venues

    @markers = @venues.map do |venue|
      {
        lat: venue.latitude,
        lng: venue.longitude,
        info_window: render_to_string(partial: "pages/info_window", locals: {venue: venue }),
        image_url: helpers.asset_url("marker-stroked.svg")
      }
    end
  end

  def edit; end

  def preview
    @journey_venues = @journey.venues
    @markers = @journey_venues.map do |venue|
      {
        lat: venue.latitude,
        lng: venue.longitude,
        info_window: render_to_string(partial: "pages/info_window", locals: {venue: venue }),
        image_url: helpers.asset_url("marker-stroked.svg")
      }
    end
  end

  def new; end

  def create
    @journey = Journey.new(journey_params)
    if @journey.save?
      redirect_to root_path
    else
      render "pages/home"
    end
  end

  def update
    @journey.update(journey_params)
    redirect_to journey_path(@journey)
  end

  private

  def find_journey
    @journey = current_user.journeys.last
  end

  def find_venue
    @venue = Venue.find(params[:id])
  end

  def journey_params
    params.require(:journey).permit(:description, :user)
  end
end

app/views/journeys/_edit.html.erb
<%= simple_form_for [ @restaurant, @review ] do |f| %>
  <%= f.input :description %>
  <%= f.submit "Submit" %>
<% end %>

app/views/journeys/_index.html.erb
<%= form_for(@journey) do |f| %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.submit %>
<% end %>

app/views/journeys/index.html.erb
<div class="container journeys-container p-0 mt-3">
  <div class="journey-header">
  </div>
  <% @journeys.each do |journey| %>
      <% journey.venues.each do |venue|%>
        <div class="journey-card">
          <div class="journey-card-image" style="">
            <p class="venue-card-image-header"><%= "#{journey.description}'s view from front"%></p>
          </div>
          <div class="journey-card-description">
            <p class="journey-card-description-header"><%= venue.name.capitalize %></p>
            <%# <p class="journey-card-description-body"><%= venue.description </p> %>
            <div class="d-flex">
              <%= link_to "View", journey_path(journey), class: "btn journey-button" %>
            </div>
          </div>
        </div>
      <% end %>
  <% end %>
</div>

app/views/journeys/preview.html.erb
<div class="journey-overview-map">
  <div data-controller="mapDisplay">
    <div class="map-border" data-mapDisplay-target="mapb">
      <div style="width: 100vw; height: 100vh;" class="map"
        data-controller="mapbox"
        data-mapbox-journey-show-value="show"
        data-mapbox-markers-value="<%= @markers.to_json %>"
        data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>
<div class="instructions-holder" data-controller="instructions">
  <div class="internal-container">
    <div class="container" >
      <div class="floating-button">
        <div class="btn" id="homepage-map-button" data-instructions-target="button" data-action="click->instructions#displayInstructions">Details</div>
      </div>
    </div>
    <div class="instruction-container d-none" data-instructions-target="instructionsDiv">
      <div class="instruction-div" id="instructions"></div>
    </div>
  </div>
</div>

app/views/journeys/show.html.erb
<div class="journey-overview-map">
  <div data-controller="mapDisplay" class="py-16">
    <div class="map-border" data-mapDisplay-target="mapb">
      <div style="width: 100%; height: 45vh;" class="map"
        data-controller="mapbox"
        data-mapbox-journey-show-value="show"
        data-mapbox-markers-value="<%= @markers.to_json %>"
        data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>
<div class="container journeys-container p-0 m-0">
  <div class="journey-header">
    <h2>Your Journey</h2>
  </div>
  <% @unsplash_photo_search =  Unsplash::Photo.search("restaurant") %>
  <% @journey_venues.each do |journey_venue| %>
    <% @photo_url = @unsplash_photo_search.sample[:urls].raw%>
    <% @photo_url = "https://ychef.files.bbci.co.uk/976x549/p04dgkm4.jpg" if @photo_url.nil? || @photo_url.empty?%>
    <% @style = "background-image: url(#{@photo_url});" %>
    <div class="venue-journey-card">
      <div class="venue-card-image"  style="<%= @style %>"></div>
      <div class="journey-venue-card-description">
        <p class="venue-card-description-header"><%= journey_venue.venue.name %></p>
        <p><%= journey_venue.venue.address %></p>
        <div class="stick-bottom">
          <div id="journey-button-holder">
            <%= link_to venue_path(journey_venue.venue), id: "journey-preview" do %>
              <i class="gg-eye"></i>
            <% end %>
            <%# <%= link_to "Remove", journey_venue_path(venue), method: :delete, id: "journey-reject-button"%>
            <%= link_to journey_venue_path(journey_venue, journey_id: {id: @journey.id}), method: :delete, class: "btn btn-success", id: "reject-venue" do %>
              <i class="gg-trash"></i>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div class="main-button">
    <%= link_to "Directions", preview_path(@journey), class: "btn", id: "main-button" %>
  </div>
</div>